id: human_pose_classifier
name: Pose Classifier
name[zh]: 人体姿态分类
version: 1.0.1
author: Taorye@Sipeed
icon: icon.json
desc: Detect human body 17 keypoints and then classify the pose.
files:
  - app.yaml
  - icon.json
  - main.py
  - PoseEstimation.py
